baseurl = "https://pairprogramming.live"
title = "pairprogramming.live"

publishdir = "docs"
theme = "hugo-coder"

DefaultContentLanguage = "ru"

googleAnalytics = "UA-114230346-2"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    home_h1 = "Pair programming show"
    home_h2 = "instead boring coding streams"
    home_text = "Read our manifest"
    description = ""
    keywords = "programming,broadcasting,stream"

    hideCredits = true
    hideCopyright = true
    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Twitch"
    weight = 1
    url = "https://www.twitch.tv/directory/game/programming"

[[params.social]]
    name = "Github"
    weight = 3
    url = "https://github.com/AndreyBronin/pairprogramming.live"

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"

[[menu.main]]
    name = "Manifest"
    weight = 2
    url = "/Manifest/"

[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"

[[menu.main]]
    name = "FAQ"
    weight = 4
    url  = "/faq/"

[[menu.main]]
    name = "Tools"
    weight = 5
    url  = "/tools/"

[Languages]
[Languages.en]
    title = "pairprogramming.live"
    weight = 1
    languageName = "EN"
[Languages.en.params]
    home_h1 = "Let's develop open source projects in live show format"
    home_h2 = "Down with boring coding live streams! Programming practice should be interesting and fun"
    home_text = "Read our manifest"
    description = ""
    keywords = "programming,broadcasting,stream"

[Languages.ru]
    title = "#pairprogrammingshow"
    weight = 2
    languageName = "RU"
[Languages.ru.params]
    home_h1 = "Разрабатывай открытые проекты в формате онлайн шоу"
    home_h2 = "Долой скучные программерские стримы! Разработка должна быть интересной и доставлять удовольствие"
    home_text = "Прочти наш манифест"
    description = ""
    keywords = "programming,broadcasting,stream"

[[Languages.ru.menu.main]]
    url = "/"
    name = "Главная"
    weight = 1

[[Languages.ru.menu.main]]
    url = "/Manifest/"
    name = "Манифест"
    weight = 2

[[Languages.ru.menu.main]]
    url = "/posts/"
    name = "Блог"
    weight = 3

[[Languages.ru.menu.main]]
    name = "ЧаВо"
    weight = 4
    url  = "/faq/"

[[Languages.ru.menu.main]]
    name = "Инструменты"
    weight = 5
    url  = "/tools/"
