baseurl = "http://pairprogramming.live"
title = "Парное программирование живые трансляции"

publishdir = "docs"
theme = "hugo-coder"

DefaultContentLanguage = "en"

googleAnalytics = "UA-114230346-2"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "Pair programming live show"
    info = "information block"
    description = ""
    keywords = "programming,broadcasting,stream"

    hideCredits = true
    hideCopyright = true
    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Twitch"
    weight = 1
    url = "https://www.twitch.tv/directory/game/Creative/programming"

[[params.social]]
    name = "Telegram"
    weight = 2
    url = "https://telegram.org"

[[params.social]]
    name = "Github"
    weight = 3
    url = "https://github.com/AndreyBronin/pairprogramming.live"

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"

[[menu.main]]
    name = "Manifest"
    weight = 2
    url = "/Manifest/"

[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"

[Languages]
[Languages.ru]
    title = "#pairprogrammingshow"
    weight = 2
    languageName = "RU"
[Languages.ru.params]
    author = "Шоу парного программирования"
    info = "Живые трансляции"
    description = ""
    keywords = "programming,broadcasting,stream"

[[Languages.ru.menu.main]]
    url = "/"
    name = "Главная"
    weight = 1

[[Languages.ru.menu.main]]
    url = "/Manifest/"
    name = "Манифест"
    weight = 2

[[Languages.ru.menu.main]]
    url = "/posts/"
    name = "Блог"
    weight = 3

[Languages.en]
    title = "#pairprogrammingshow"
    weight = 1
    languageName = "EN"
[Languages.en.params]
    author = "Pair programming live show"
    info = "information block"
    description = ""
    keywords = "programming,broadcasting,stream"
